/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.util.Scanner;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextField;
import javax.swing.ScrollPaneConstants;

import Tree.ManejadorDD;
import java.util.List;
import Tree.Arbol;


/**
 *
 * @author yeico
 */
public class Consola extends javax.swing.JFrame {

    /**
     * Creates new form Consola
     */
    int posTextoConsola =  0;
    JPanel panel = new JPanel();
    String directorio = "systemFile/user >";
    public Consola() {
        initComponents();
        panel.setOpaque(true);
        panel.setBackground(new Color (133,33,66));
        JScrollPane scrollPane = new JScrollPane();
        scrollPane.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        scrollPane.setVerticalScrollBarPolicy(ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        scrollPane.setBounds(0, 0, jPanel1.getWidth(), jPanel1.getHeight());
        panel.setPreferredSize(new Dimension(1000,1000));
        scrollPane.setViewportView(panel);
        jPanel1.add(scrollPane);
        panel.setLayout(null);
        
        JLabel label = crearLabel(directorio.length());
        JTextField textField = crearTextField(directorio.length());
        label.setText(directorio);
        panel.add(label);
        panel.add(textField);
        panel.updateUI();
        posTextoConsola+=50;
        
    }
    public JLabel crearLabel(int tamanox){
        tamanox = tamanox*7;
        JLabel var = new JLabel();
        var.setOpaque(true);
        var.setBackground(new Color (133,33,66));
        var.setBounds(10, posTextoConsola, tamanox, 30);
        return var;   
    }
    public JTextField crearTextField(int tamanox){
        JTextField txtInput = new JTextField();
        txtInput.setOpaque(true);
        txtInput.setBackground(new Color (133,33,66));
        txtInput.setBorder(null);
        txtInput.setBounds((tamanox*7)+15,posTextoConsola,500,30);
        eventosTeclado(txtInput);
        return txtInput;
    }
    public void eventosTeclado(JTextField varText){
        KeyListener eventoTeclado = new KeyListener() {
            @Override
            public void keyPressed(KeyEvent ke) { 
            }
            @Override
            public void keyTyped(KeyEvent ke) {
            }
            @Override
            public void keyReleased(KeyEvent ke) {
                if(ke.getKeyChar() == '\n'){
                    varText.setEditable(false);
                    JLabel label = crearLabel(varText.getText().length());
                    JTextField textField = crearTextField(varText.getText().length());
                    label.setText(varText.getText());
                    panel.add(label);
                    panel.add(textField);
                    panel.updateUI();
                    posTextoConsola+=50;
                }
            }
        };
        varText.addKeyListener(eventoTeclado);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 0, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 852, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 367, Short.MAX_VALUE)
        );

        jButton1.setText("Opcion1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Opcion2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private static void mainAux(){
        //ManejadorDD.crearDiscoDuro();
        
        //List<Integer> espaciosUsados = ManejadorDD.insertarEspacio("Nomb");
        //ManejadorDD.insertarEspacio("as");
        //ManejadorDD.eliminarEspacios(espaciosUsados);
        //ManejadorDD.insertarEspacio("jajaXD");
        
        Arbol arbol = new Arbol(1,1);
        try{
            arbol.copy("C:/Users/aryel/OneDrive/Documents/GitHub/File_System_Operativos/Fyle_system/archivosReales", "FS:/");
            arbol.copy("FS:/archivosReales", "FS:/archivosReales/Cosa");
        } catch(Exception e) {}
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                mainAux();
                //new Consola().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
